name: Reconcile Action for Eigenbot
description: TODO
branding:
  icon: check-square
  color: green
inputs:
  version:
    description: TODO
    default: latest
  access-key:
    description: Eigenbot Account Secret
    required: true
  github-token:
    description: GitHub Access Token
    required: true
  repo:
    description: TODO
  manifest-id:
    description: TODO
runs:
  using: composite
  steps:
    - run: |
        ${{ github.action_path }}/bin/reconcile \
          -access-key "${{ inputs.access-key }}" \
          -github-token "${{ inputs.github-token }}" \
          -repo "${{ inputs.repo }}" \
          -manifest-id "${{ inputs.manifest-id }}"
      shell: bash
      env:
        VERSION: ${{ inputs.version }}
        GH_TOKEN: ${{ inputs.github-token }}
