name: Reconcile Action for Eigenbot
description: TODO
branding:
  icon: check-square
  color: green
inputs:
  access-key:
    description: Eigenbot Account Secret
    required: true
  github-token:
    description: GitHub Access Token
    required: true
  repo:
    description: TODO
  manifest-id:
    description: TODO
runs:
  using: node16
  main: ./dist/main.js
